spring.data.mongodb.uri=mongodb+srv://komakulapragnay_:Project%402004@cluster0.deotok2.mongodb.net/careerpathdb?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=careerpathdb
server.port=8080
spring.data.mongodb.ssl.enabled=false